# Generated by Django 6.0.6 on 2026-06-22 18:56

import accounts.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(blank=True, db_column='passwordHash')),
                ('name', models.TextField()),
                ('role', models.TextField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher')], default='TEACHER')),
                ('phone', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('school', models.ForeignKey(blank=True, db_column='schoolId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schools.school')),
            ],
            options={
                'db_table': '"User"',
            },
        ),
    ]
