# Generated by Django 6.0.6 on 2026-06-24 18:28

from django.db import migrations


def add_enum_values(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS \'SUPER_ADMIN\'')
            cursor.execute('ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS \'PRINCIPAL\'')
            cursor.execute('ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS \'VICE_PRINCIPAL\'')
            cursor.execute('ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS \'SECRETARY\'')
            cursor.execute('ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS \'ACCOUNTANT\'')
            cursor.execute('ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS \'CLASS_TEACHER\'')
            cursor.execute('ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS \'SUBJECT_TEACHER\'')


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(add_enum_values, migrations.RunPython.noop, atomic=False),
    ]
