# Generated by Django 6.0.6 on 2026-06-24 18:28

from django.db import migrations


def convert_teacher_role(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='TEACHER').update(role='CLASS_TEACHER')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(convert_teacher_role, reverse_code=migrations.RunPython.noop),
    ]
