# Generated by Django 6.0.6 on 2026-06-24 19:32

from django.db import migrations


def update_enum_and_data(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS \'TEACHER\'')
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role__in=['CLASS_TEACHER', 'SUBJECT_TEACHER']).update(role='TEACHER')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_convert_teacher_role'),
    ]

    operations = [
        migrations.RunPython(update_enum_and_data, migrations.RunPython.noop),
    ]
