# Generated by Django 6.0.6 on 2026-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_simplify_teacher_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('SECRETARY', 'Secretary'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher')], default='ADMIN'),
        ),
    ]
