# Generated by Django 6.0.6 on 2026-06-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], null=True),
        ),
    ]
