# Generated by Django 6.0.6 on 2026-06-22 18:56

import accounts.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.TextField(db_column='firstName')),
                ('last_name', models.TextField(db_column='lastName')),
                ('reg_number', models.TextField(db_column='regNumber')),
                ('parent_pin_hash', models.TextField(db_column='parentPinHash')),
                ('status', models.TextField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('GRADUATED', 'Graduated'), ('REPEATING', 'Repeating')], default='ACTIVE')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('class_group', models.ForeignKey(db_column='classId', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.classgroup')),
                ('school', models.ForeignKey(db_column='schoolId', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
            ],
            options={
                'db_table': '"Student"',
                'unique_together': {('school', 'reg_number')},
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('academic_year', models.TextField(db_column='academicYear')),
                ('annual_cumulative', models.FloatField(blank=True, db_column='annualCumulative', null=True)),
                ('annual_position', models.IntegerField(blank=True, db_column='annualPosition', null=True)),
                ('status', models.TextField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('GRADUATED', 'Graduated'), ('REPEATING', 'Repeating')], default='ACTIVE')),
                ('promoted_at', models.DateTimeField(blank=True, db_column='promotedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('class_group', models.ForeignKey(db_column='classId', on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='classes.classgroup')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
            ],
            options={
                'db_table': '"AcademicRecord"',
            },
        ),
    ]
