# Generated by Django 6.0.6 on 2026-06-22 18:56

import accounts.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('class_group', models.ForeignKey(db_column='classId', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.classgroup')),
                ('school', models.ForeignKey(db_column='schoolId', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school')),
            ],
            options={
                'db_table': '"Subject"',
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='students.student')),
                ('subject', models.ForeignKey(db_column='subjectId', on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='subjects.subject')),
            ],
            options={
                'db_table': '"StudentSubject"',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
