# Generated by Django 6.0.6 on 2026-06-22 18:56

import accounts.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('email', models.TextField()),
                ('logo_url', models.TextField(blank=True, db_column='logoUrl', null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': '"School"',
            },
        ),
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('pass_threshold', models.IntegerField(db_column='passThreshold', default=50)),
                ('distinction_threshold', models.IntegerField(db_column='distinctionThreshold', default=75)),
                ('graduation_type', models.TextField(db_column='graduationType', default='passAll')),
                ('graduation_min_cumulative', models.IntegerField(db_column='graduationMinCumulative', default=50)),
                ('rating_scale', models.JSONField(db_column='ratingScale', default=list)),
                ('affective_traits', models.JSONField(db_column='affectiveTraits', default=list)),
                ('psychomotor_skills', models.JSONField(db_column='psychomotorSkills', default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('school', models.ForeignKey(db_column='schoolId', on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='schools.school')),
            ],
            options={
                'db_table': '"SchoolConfig"',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField(choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third')])),
                ('academic_year', models.TextField(db_column='academicYear')),
                ('is_current', models.BooleanField(db_column='isCurrent', default=False)),
                ('starts_at', models.DateTimeField(db_column='startsAt')),
                ('ends_at', models.DateTimeField(db_column='endsAt')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('school', models.ForeignKey(db_column='schoolId', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='schools.school')),
            ],
            options={
                'db_table': '"Term"',
            },
        ),
        migrations.CreateModel(
            name='ExamPeriod',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('MID_TERM', 'Mid Term'), ('TERMINAL', 'Terminal')])),
                ('name', models.TextField()),
                ('is_open', models.BooleanField(db_column='isOpen', default=False)),
                ('starts_at', models.DateTimeField(db_column='startsAt')),
                ('ends_at', models.DateTimeField(db_column='endsAt')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('term', models.ForeignKey(db_column='termId', on_delete=django.db.models.deletion.CASCADE, related_name='exam_periods', to='schools.term')),
            ],
            options={
                'db_table': '"ExamPeriod"',
            },
        ),
    ]
