# Generated by Django 6.0.6 on 2026-06-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_column='endsAt', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_column='startsAt', null=True),
        ),
    ]
