# Generated by Django 6.0.6 on 2026-06-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_make_term_dates_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='graduation_rules',
            field=models.JSONField(blank=True, db_column='graduationRules', default=dict),
        ),
    ]
