# Generated by Django 6.0.6 on 2026-06-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_add_graduation_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examperiod',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_column='endsAt', null=True),
        ),
        migrations.AlterField(
            model_name='examperiod',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_column='startsAt', null=True),
        ),
    ]
