# Generated by Django 6.0.6 on 2026-06-23 10:43

import accounts.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_make_examperiod_dates_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examperiod',
            name='ends_at',
            field=models.DateField(blank=True, db_column='endsAt', null=True),
        ),
        migrations.AlterField(
            model_name='examperiod',
            name='starts_at',
            field=models.DateField(blank=True, db_column='startsAt', null=True),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('MID_TERM', 'Mid Term Break'), ('END_OF_TERM', 'End of Term Break')])),
                ('starts_at', models.DateField(blank=True, db_column='startsAt', null=True)),
                ('ends_at', models.DateField(blank=True, db_column='endsAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('term', models.ForeignKey(db_column='termId', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='schools.term')),
            ],
            options={
                'db_table': '"Holiday"',
            },
        ),
    ]
