# Generated by Django 6.0.6 on 2026-06-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_fix_exam_type_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='print_permissions',
            field=models.JSONField(blank=True, db_column='printPermissions', default=list),
        ),
    ]
