# Generated by Django 6.0.6 on 2026-06-22 18:56

import accounts.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('section', models.TextField(choices=[('NURSERY', 'Nursery'), ('PRIMARY', 'Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary'), ('SENIOR_SECONDARY', 'Senior Secondary')])),
                ('sheet_type', models.TextField(choices=[('NURSERY_EARLY', 'Nursery Early'), ('PRIMARY', 'Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary'), ('SENIOR_SECONDARY_EXTENDED', 'Senior Secondary Extended')], db_column='sheetType', default='PRIMARY')),
                ('order', models.IntegerField()),
                ('academic_year', models.TextField(db_column='academicYear')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('school', models.ForeignKey(db_column='schoolId', on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='schools.school')),
                ('teacher', models.ForeignKey(blank=True, db_column='teacherId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"Class"',
            },
        ),
    ]
