# Generated by Django 6.0.6 on 2026-06-22 18:56

import accounts.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('CLASS_TEST', 'Class Test'), ('MID_TERM_EXAM', 'Mid Term Exam'), ('TERMINAL_EXAM', 'Terminal Exam')])),
                ('name', models.TextField()),
                ('max_score', models.IntegerField(db_column='maxScore')),
                ('score_obtained', models.IntegerField(db_column='scoreObtained')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('exam_period', models.ForeignKey(db_column='examPeriodId', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.examperiod')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.student')),
                ('student_subject', models.ForeignKey(db_column='studentSubjectId', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='subjects.studentsubject')),
            ],
            options={
                'db_table': '"Assessment"',
            },
        ),
        migrations.CreateModel(
            name='ScoreSummary',
            fields=[
                ('id', accounts.fields.CharIDField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('ca_score', models.FloatField(blank=True, db_column='caScore', null=True)),
                ('ca1_score', models.FloatField(blank=True, db_column='ca1Score', null=True)),
                ('ca2_score', models.FloatField(blank=True, db_column='ca2Score', null=True)),
                ('exam_score', models.FloatField(blank=True, db_column='examScore', null=True)),
                ('total_score', models.FloatField(blank=True, db_column='totalScore', null=True)),
                ('grade', models.TextField(blank=True, null=True)),
                ('subject_position', models.IntegerField(blank=True, db_column='subjectPosition', null=True)),
                ('subject_teacher_signature', models.TextField(blank=True, db_column='subjectTeacherSignature', null=True)),
                ('is_fail', models.BooleanField(blank=True, db_column='isFail', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='score_summaries', to='students.student')),
                ('student_subject', models.OneToOneField(db_column='studentSubjectId', on_delete=django.db.models.deletion.CASCADE, related_name='score_summary', to='subjects.studentsubject')),
            ],
            options={
                'db_table': '"ScoreSummary"',
            },
        ),
    ]
